{{- if and (eq .Values.policy.mode "existingSecret") (not .Values.policy.existingSecret.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bytetaper.fullname" . }}-policy
  labels:
    {{- include "bytetaper.labels" . | nindent 4 }}
type: Opaque
stringData:
  policy.yaml: |
    {{- .Values.policy.inline | nindent 4 }}
{{- end -}}
