// SPDX-FileCopyrightText: 2026 Haluan Irsad
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Commercial

#include "taperquery/policy_ir_yaml_emitter.h"

#include "taperquery/policy_ir_identity.h"
#include "taperquery/policy_ir_normalize.h"
#include "taperquery/policy_ir_printer.h"

#include <utility>

namespace bytetaper::taperquery {

PolicyIrYamlEmitResult emit_policy_ir_canonical_yaml(const TqPolicyDocument& document,
                                                     const PolicyIrYamlEmitOptions& options) {
    // Normalize first to ensure version and default fields are consistently populated
    TqPolicyDocument normalized = normalize_policy_ir(document);

    // Reuse the existing canonical printer
    std::string yaml = print_canonical_policy_ir(normalized);

    if (options.include_identity_comment) {
        std::string identity = compute_policy_document_identity(normalized);
        yaml = "# policy_identity: " + identity + "\n" + yaml;
    }

    if (options.include_header_comment) {
        yaml = "# Generated by ByteTaper TaperQuery Emitter. Do not edit manually.\n" + yaml;
    }

    return PolicyIrYamlEmitResult{ .ok = true, .yaml = std::move(yaml), .error = "" };
}

} // namespace bytetaper::taperquery
