// SPDX-FileCopyrightText: 2026 Haluan Irsad
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Commercial

//go:build !ignore_autogenerated

/*
Copyright 2026 ByteTaper Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed/License is distributed on an "AS Shared" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperAdminSpec) DeepCopyInto(out *ByteTaperAdminSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperAdminSpec.
func (in *ByteTaperAdminSpec) DeepCopy() *ByteTaperAdminSpec {
	if in == nil {
		return nil
	}
	out := new(ByteTaperAdminSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperGateway) DeepCopyInto(out *ByteTaperGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperGateway.
func (in *ByteTaperGateway) DeepCopy() *ByteTaperGateway {
	if in == nil {
		return nil
	}
	out := new(ByteTaperGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ByteTaperGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperGatewayList) DeepCopyInto(out *ByteTaperGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ByteTaperGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperGatewayList.
func (in *ByteTaperGatewayList) DeepCopy() *ByteTaperGatewayList {
	if in == nil {
		return nil
	}
	out := new(ByteTaperGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ByteTaperGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperGatewaySpec) DeepCopyInto(out *ByteTaperGatewaySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Image.DeepCopyInto(&out.Image)
	in.Policy.DeepCopyInto(&out.Policy)
	in.L2Cache.DeepCopyInto(&out.L2Cache)
	out.Runtime = in.Runtime
	out.Metrics = in.Metrics
	out.Admin = in.Admin
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperGatewaySpec.
func (in *ByteTaperGatewaySpec) DeepCopy() *ByteTaperGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(ByteTaperGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperGatewayStatus) DeepCopyInto(out *ByteTaperGatewayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperGatewayStatus.
func (in *ByteTaperGatewayStatus) DeepCopy() *ByteTaperGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(ByteTaperGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperImageSpec) DeepCopyInto(out *ByteTaperImageSpec) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperImageSpec.
func (in *ByteTaperImageSpec) DeepCopy() *ByteTaperImageSpec {
	if in == nil {
		return nil
	}
	out := new(ByteTaperImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperL2CacheSpec) DeepCopyInto(out *ByteTaperL2CacheSpec) {
	*out = *in
	in.Persistence.DeepCopyInto(&out.Persistence)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperL2CacheSpec.
func (in *ByteTaperL2CacheSpec) DeepCopy() *ByteTaperL2CacheSpec {
	if in == nil {
		return nil
	}
	out := new(ByteTaperL2CacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperMetricsSpec) DeepCopyInto(out *ByteTaperMetricsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperMetricsSpec.
func (in *ByteTaperMetricsSpec) DeepCopy() *ByteTaperMetricsSpec {
	if in == nil {
		return nil
	}
	out := new(ByteTaperMetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperPersistenceSpec) DeepCopyInto(out *ByteTaperPersistenceSpec) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperPersistenceSpec.
func (in *ByteTaperPersistenceSpec) DeepCopy() *ByteTaperPersistenceSpec {
	if in == nil {
		return nil
	}
	out := new(ByteTaperPersistenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperPolicySpec) DeepCopyInto(out *ByteTaperPolicySpec) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperPolicySpec.
func (in *ByteTaperPolicySpec) DeepCopy() *ByteTaperPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ByteTaperPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteTaperRuntimeSpec) DeepCopyInto(out *ByteTaperRuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteTaperRuntimeSpec.
func (in *ByteTaperRuntimeSpec) DeepCopy() *ByteTaperRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(ByteTaperRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}
