apiVersion: v2
name: bytetaper
description: A Helm chart for deploying the ByteTaper API Performance Gateway runtime
type: application
version: 0.1.0
appVersion: "v0.1.0"
home: https://github.com/ByteTaper/bytetaper
sources:
  - https://github.com/ByteTaper/bytetaper
keywords:
  - bytetaper
  - gateway
  - performance
  - proxy
maintainers:
  - name: Haluan Irsad
    email: haluan.irsad@gmail.com
